version: 2
updates:
  # Update Python packages in pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "torres-alexis"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope" 