name: dp_tools
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=3.0
  - samtools
  - parallel
  - curl
  - pytest>=9
  - pip
  - pip:
    - git+https://github.com/torres-alexis/dp_tools.git@v1.3.12
